### PR TITLE
ENH: Bump ITK to make Python packages compatible

### PR DESCRIPTION
**Pull request by PranjalSahu**

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
@PranjalSahu thanks!

**Comment by thewtex** [comment]
@PranjalSahu please try: https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction for maintainability

**Comment by PranjalSahu** [comment]
@tbirdso Yes, I saw your commit. I will do those changes in this PR.
I needed a pip package to test something quick which I got from the Actions.

**Review by dzenanz — APPROVED** [review]

**Review by tbirdso — APPROVED** [review]

**Comment by tbirdso** [comment]
Recommend re-running Linux Python jobs once remaining jobs complete

**Comment by PranjalSahu** [comment]
I don't have merge permissions for this repo.

**Pull request merged**
