### PR TITLE
STYLE: Add ITK prefix to testing macros

### PR DESCRIPTION
**Pull request by jhlegarreta**

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@zachary-williamson @DVigneault @HastingsGreer reviews are welcome. Thanks.

**Comment by thewtex** [comment]
We could use a newer commit from ITK Git `master` here:

https://github.com/InsightSoftwareConsortium/ITKCuberille/blob/4ed1e797a6737343779b01b7035cc394e8dd8bf7/test/azure-pipelines.yml#L2

to make the Azure build pass.

**Comment by thewtex** [comment]
Thanks again @jhlegarreta  for these improvements!

**Comment by jhlegarreta** [comment]
Thanks both @dzenanz and @thewtex for keeping up with the effort !

**Pull request merged**
