### PR TITLE
STYLE: Use Macro for Function Deletion

### PR DESCRIPTION
**Pull request by zachary-williamson**
@hjmjohnson

### CODE REVIEW

**Comment by thewtex** [comment]
@zachary-williamson Thanks!

To allow the CI testing build to pass, could the version of ITK please also be updated? This involves updating this line:

 https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/blob/master/test/Docker/Dockerfile#L25

and also adding a build step a la

  https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/blob/c14ef005dcd2d84f7856fc848b3ed47bdaae3bd1/circle.yml#L9

**Comment by zachary-williamson** [comment]
@thewtex Sure thing, Should I use the same version of ITK from your example, or the newest release version?

**Comment by zachary-williamson** [comment]
This is the second time the test build has timed out, I think the version of ITK needed for this patch just takes too long to build.  

@thewtex 
In the interest of shortening the build time, is it absolutely necessary to build this with the python wrappings just for testing? It seems like that's whats eating up all the time.

**Comment by thewtex** [comment]
@zachary-williamson The timeout on the build should be increase like this: https://github.com/KitwareMedical/TubeTK/blob/0df10c65a8442b7fa46e6e17da6b7cea715fef66/circle.yml#L15

**Comment by zachary-williamson** [comment]
@thewtex The build is taking longer than 2 hours which is the limit for circleci, adjusting the timeout on that command won't help

**Comment by thewtex** [comment]
@zachary-williamson Looking at the other pull requests, I investigated this issue before:

  https://github.com/InsightSoftwareConsortium/ITKCuberille/pull/16

The build is actually not taking that long, but it is hanging at a certain point. I could not reproduce it locally, and I suspect it is an issue with CircleCI.

I think it is fine to disable the wrapping for now -- we could re-enable it after CircleCI is fixed.

**Comment by thewtex** [comment]
Thanks!

**Pull request merged**
